# Generated by Django 3.2.13 on 2023-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
