# Generated by Django 3.2.13 on 2023-10-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20231004_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secret_key',
        ),
    ]
