# Generated by Django 3.2.13 on 2023-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20231004_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
