# Generated by Django 3.2.13 on 2023-10-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret_key',
        ),
    ]
