# Generated by Django 3.2.13 on 2023-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
